[Wed Nov 02 22:32:02.123110 2016] [wsgi:error] [pid 2033:tid 139625821628160] [client 71.42.119.84:63396] mod_wsgi (pid=2033): Target WSGI script '/var/www/cs373f-idb/app.wsgi' cannot be loaded as Python module.
[Wed Nov 02 22:32:02.123308 2016] [wsgi:error] [pid 2033:tid 139625821628160] [client 71.42.119.84:63396] mod_wsgi (pid=2033): Exception occurred processing WSGI script '/var/www/cs373f-idb/app.wsgi'.
[Wed Nov 02 22:32:02.132296 2016] [wsgi:error] [pid 2033:tid 139625821628160] [client 71.42.119.84:63396] Traceback (most recent call last):
[Wed Nov 02 22:32:02.132444 2016] [wsgi:error] [pid 2033:tid 139625821628160] [client 71.42.119.84:63396]   File "/var/www/cs373f-idb/app.wsgi", line 7, in <module>
[Wed Nov 02 22:32:02.132468 2016] [wsgi:error] [pid 2033:tid 139625821628160] [client 71.42.119.84:63396]     from app.app import app as application
[Wed Nov 02 22:32:02.132499 2016] [wsgi:error] [pid 2033:tid 139625821628160] [client 71.42.119.84:63396]   File "/var/www/cs373f-idb/app/app.py", line 8, in <module>
[Wed Nov 02 22:32:02.132513 2016] [wsgi:error] [pid 2033:tid 139625821628160] [client 71.42.119.84:63396]     import models
[Wed Nov 02 22:32:02.132572 2016] [wsgi:error] [pid 2033:tid 139625821628160] [client 71.42.119.84:63396] ImportError: No module named 'models'
[Wed Nov 02 22:32:02.445450 2016] [wsgi:error] [pid 2034:tid 139625712523008] [client 71.42.119.84:63399] mod_wsgi (pid=2034): Target WSGI script '/var/www/cs373f-idb/app.wsgi' cannot be loaded as Python module.
[Wed Nov 02 22:32:02.445588 2016] [wsgi:error] [pid 2034:tid 139625712523008] [client 71.42.119.84:63399] mod_wsgi (pid=2034): Exception occurred processing WSGI script '/var/www/cs373f-idb/app.wsgi'.
[Wed Nov 02 22:32:02.446360 2016] [wsgi:error] [pid 2034:tid 139625712523008] [client 71.42.119.84:63399] Traceback (most recent call last):
[Wed Nov 02 22:32:02.446431 2016] [wsgi:error] [pid 2034:tid 139625712523008] [client 71.42.119.84:63399]   File "/var/www/cs373f-idb/app.wsgi", line 7, in <module>
[Wed Nov 02 22:32:02.446460 2016] [wsgi:error] [pid 2034:tid 139625712523008] [client 71.42.119.84:63399]     from app.app import app as application
[Wed Nov 02 22:32:02.446478 2016] [wsgi:error] [pid 2034:tid 139625712523008] [client 71.42.119.84:63399]   File "/var/www/cs373f-idb/app/app.py", line 8, in <module>
[Wed Nov 02 22:32:02.446487 2016] [wsgi:error] [pid 2034:tid 139625712523008] [client 71.42.119.84:63399]     import models
[Wed Nov 02 22:32:02.446543 2016] [wsgi:error] [pid 2034:tid 139625712523008] [client 71.42.119.84:63399] ImportError: No module named 'models'
[Wed Nov 02 23:00:29.563121 2016] [wsgi:error] [pid 2935:tid 140385636579072] [client 71.42.119.84:63749] mod_wsgi (pid=2935): Target WSGI script '/var/www/cs373f-idb/app.wsgi' cannot be loaded as Python module.
[Wed Nov 02 23:00:29.563324 2016] [wsgi:error] [pid 2935:tid 140385636579072] [client 71.42.119.84:63749] mod_wsgi (pid=2935): Exception occurred processing WSGI script '/var/www/cs373f-idb/app.wsgi'.
[Wed Nov 02 23:00:29.564336 2016] [wsgi:error] [pid 2935:tid 140385636579072] [client 71.42.119.84:63749] Traceback (most recent call last):
[Wed Nov 02 23:00:29.564391 2016] [wsgi:error] [pid 2935:tid 140385636579072] [client 71.42.119.84:63749]   File "/var/www/cs373f-idb/app.wsgi", line 7, in <module>
[Wed Nov 02 23:00:29.564403 2016] [wsgi:error] [pid 2935:tid 140385636579072] [client 71.42.119.84:63749]     from app.app import app as application
[Wed Nov 02 23:00:29.564419 2016] [wsgi:error] [pid 2935:tid 140385636579072] [client 71.42.119.84:63749]   File "/var/www/cs373f-idb/app/app.py", line 8, in <module>
[Wed Nov 02 23:00:29.564427 2016] [wsgi:error] [pid 2935:tid 140385636579072] [client 71.42.119.84:63749]     import models
[Wed Nov 02 23:00:29.564464 2016] [wsgi:error] [pid 2935:tid 140385636579072] [client 71.42.119.84:63749] ImportError: No module named 'models'
[Thu Nov 03 00:08:41.990225 2016] [wsgi:error] [pid 4319:tid 140183898941184] [client 71.42.119.84:63610] mod_wsgi (pid=4319): Target WSGI script '/var/www/cs373f-idb/app.wsgi' cannot be loaded as Python module.
[Thu Nov 03 00:08:41.990393 2016] [wsgi:error] [pid 4319:tid 140183898941184] [client 71.42.119.84:63610] mod_wsgi (pid=4319): Exception occurred processing WSGI script '/var/www/cs373f-idb/app.wsgi'.
[Thu Nov 03 00:08:41.991035 2016] [wsgi:error] [pid 4319:tid 140183898941184] [client 71.42.119.84:63610] Traceback (most recent call last):
[Thu Nov 03 00:08:41.991086 2016] [wsgi:error] [pid 4319:tid 140183898941184] [client 71.42.119.84:63610]   File "/var/www/cs373f-idb/app.wsgi", line 7, in <module>
[Thu Nov 03 00:08:41.991097 2016] [wsgi:error] [pid 4319:tid 140183898941184] [client 71.42.119.84:63610]     from app.app import app as application
[Thu Nov 03 00:08:41.991112 2016] [wsgi:error] [pid 4319:tid 140183898941184] [client 71.42.119.84:63610]   File "/var/www/cs373f-idb/app/app.py", line 8, in <module>
[Thu Nov 03 00:08:41.991119 2016] [wsgi:error] [pid 4319:tid 140183898941184] [client 71.42.119.84:63610]     import models
[Thu Nov 03 00:08:41.991153 2016] [wsgi:error] [pid 4319:tid 140183898941184] [client 71.42.119.84:63610] ImportError: No module named 'models'
[Thu Nov 03 00:18:42.424981 2016] [wsgi:error] [pid 4485:tid 140443934906112] [client 71.42.119.84:63660] mod_wsgi (pid=4485): Target WSGI script '/var/www/cs373f-idb/app.wsgi' cannot be loaded as Python module.
[Thu Nov 03 00:18:42.425106 2016] [wsgi:error] [pid 4485:tid 140443934906112] [client 71.42.119.84:63660] mod_wsgi (pid=4485): Exception occurred processing WSGI script '/var/www/cs373f-idb/app.wsgi'.
[Thu Nov 03 00:18:42.425494 2016] [wsgi:error] [pid 4485:tid 140443934906112] [client 71.42.119.84:63660] Traceback (most recent call last):
[Thu Nov 03 00:18:42.425541 2016] [wsgi:error] [pid 4485:tid 140443934906112] [client 71.42.119.84:63660]   File "/var/www/cs373f-idb/app.wsgi", line 7, in <module>
[Thu Nov 03 00:18:42.425552 2016] [wsgi:error] [pid 4485:tid 140443934906112] [client 71.42.119.84:63660]     from app.app import app as application
[Thu Nov 03 00:18:42.425581 2016] [wsgi:error] [pid 4485:tid 140443934906112] [client 71.42.119.84:63660]   File "/var/www/cs373f-idb/app/app.py", line 8
[Thu Nov 03 00:18:42.425603 2016] [wsgi:error] [pid 4485:tid 140443934906112] [client 71.42.119.84:63660]     import app/models
[Thu Nov 03 00:18:42.425638 2016] [wsgi:error] [pid 4485:tid 140443934906112] [client 71.42.119.84:63660]               ^
[Thu Nov 03 00:18:42.425659 2016] [wsgi:error] [pid 4485:tid 140443934906112] [client 71.42.119.84:63660] SyntaxError: invalid syntax
[Thu Nov 03 00:18:42.828931 2016] [wsgi:error] [pid 4486:tid 140443752822528] [client 71.42.119.84:63666] mod_wsgi (pid=4486): Target WSGI script '/var/www/cs373f-idb/app.wsgi' cannot be loaded as Python module.
[Thu Nov 03 00:18:42.829080 2016] [wsgi:error] [pid 4486:tid 140443752822528] [client 71.42.119.84:63666] mod_wsgi (pid=4486): Exception occurred processing WSGI script '/var/www/cs373f-idb/app.wsgi'.
[Thu Nov 03 00:18:42.829538 2016] [wsgi:error] [pid 4486:tid 140443752822528] [client 71.42.119.84:63666] Traceback (most recent call last):
[Thu Nov 03 00:18:42.829589 2016] [wsgi:error] [pid 4486:tid 140443752822528] [client 71.42.119.84:63666]   File "/var/www/cs373f-idb/app.wsgi", line 7, in <module>
[Thu Nov 03 00:18:42.829600 2016] [wsgi:error] [pid 4486:tid 140443752822528] [client 71.42.119.84:63666]     from app.app import app as application
[Thu Nov 03 00:18:42.829629 2016] [wsgi:error] [pid 4486:tid 140443752822528] [client 71.42.119.84:63666]   File "/var/www/cs373f-idb/app/app.py", line 8
[Thu Nov 03 00:18:42.829655 2016] [wsgi:error] [pid 4486:tid 140443752822528] [client 71.42.119.84:63666]     import app/models
[Thu Nov 03 00:18:42.829691 2016] [wsgi:error] [pid 4486:tid 140443752822528] [client 71.42.119.84:63666]               ^
[Thu Nov 03 00:18:42.829713 2016] [wsgi:error] [pid 4486:tid 140443752822528] [client 71.42.119.84:63666] SyntaxError: invalid syntax
[Thu Nov 03 03:42:45.718097 2016] [wsgi:error] [pid 5953:tid 140141964261120] [client 71.42.119.84:64022] mod_wsgi (pid=5953): Target WSGI script '/var/www/cs373f-idb/app.wsgi' cannot be loaded as Python module.
[Thu Nov 03 03:42:45.719095 2016] [wsgi:error] [pid 5953:tid 140141964261120] [client 71.42.119.84:64022] mod_wsgi (pid=5953): Exception occurred processing WSGI script '/var/www/cs373f-idb/app.wsgi'.
[Thu Nov 03 03:42:45.720887 2016] [wsgi:error] [pid 5953:tid 140141964261120] [client 71.42.119.84:64022] Traceback (most recent call last):
[Thu Nov 03 03:42:45.721008 2016] [wsgi:error] [pid 5953:tid 140141964261120] [client 71.42.119.84:64022]   File "/var/www/cs373f-idb/app.wsgi", line 7, in <module>
[Thu Nov 03 03:42:45.721029 2016] [wsgi:error] [pid 5953:tid 140141964261120] [client 71.42.119.84:64022]     from app.app import app as application
[Thu Nov 03 03:42:45.721054 2016] [wsgi:error] [pid 5953:tid 140141964261120] [client 71.42.119.84:64022]   File "/var/www/cs373f-idb/app/app.py", line 9, in <module>
[Thu Nov 03 03:42:45.721068 2016] [wsgi:error] [pid 5953:tid 140141964261120] [client 71.42.119.84:64022]     import models
[Thu Nov 03 03:42:45.721133 2016] [wsgi:error] [pid 5953:tid 140141964261120] [client 71.42.119.84:64022] ImportError: No module named 'models'
[Thu Nov 03 03:43:02.808022 2016] [wsgi:error] [pid 5953:tid 140141989439232] [client 71.42.119.84:62944] mod_wsgi (pid=5953): Target WSGI script '/var/www/cs373f-idb/app.wsgi' cannot be loaded as Python module.
[Thu Nov 03 03:43:02.808139 2016] [wsgi:error] [pid 5953:tid 140141989439232] [client 71.42.119.84:62944] mod_wsgi (pid=5953): Exception occurred processing WSGI script '/var/www/cs373f-idb/app.wsgi'.
[Thu Nov 03 03:43:02.808393 2016] [wsgi:error] [pid 5953:tid 140141989439232] [client 71.42.119.84:62944] Traceback (most recent call last):
[Thu Nov 03 03:43:02.808457 2016] [wsgi:error] [pid 5953:tid 140141989439232] [client 71.42.119.84:62944]   File "/var/www/cs373f-idb/app.wsgi", line 7, in <module>
[Thu Nov 03 03:43:02.808471 2016] [wsgi:error] [pid 5953:tid 140141989439232] [client 71.42.119.84:62944]     from app.app import app as application
[Thu Nov 03 03:43:02.808487 2016] [wsgi:error] [pid 5953:tid 140141989439232] [client 71.42.119.84:62944]   File "/var/www/cs373f-idb/app/app.py", line 9, in <module>
[Thu Nov 03 03:43:02.808495 2016] [wsgi:error] [pid 5953:tid 140141989439232] [client 71.42.119.84:62944]     import models
[Thu Nov 03 03:43:02.808527 2016] [wsgi:error] [pid 5953:tid 140141989439232] [client 71.42.119.84:62944] ImportError: No module named 'models'
[Thu Nov 03 03:44:04.105500 2016] [wsgi:error] [pid 5953:tid 140141997831936] [client 71.42.119.84:63190] mod_wsgi (pid=5953): Target WSGI script '/var/www/cs373f-idb/app.wsgi' cannot be loaded as Python module.
[Thu Nov 03 03:44:04.105780 2016] [wsgi:error] [pid 5953:tid 140141997831936] [client 71.42.119.84:63190] mod_wsgi (pid=5953): Exception occurred processing WSGI script '/var/www/cs373f-idb/app.wsgi'.
[Thu Nov 03 03:44:04.106180 2016] [wsgi:error] [pid 5953:tid 140141997831936] [client 71.42.119.84:63190] Traceback (most recent call last):
[Thu Nov 03 03:44:04.106232 2016] [wsgi:error] [pid 5953:tid 140141997831936] [client 71.42.119.84:63190]   File "/var/www/cs373f-idb/app.wsgi", line 7, in <module>
[Thu Nov 03 03:44:04.106244 2016] [wsgi:error] [pid 5953:tid 140141997831936] [client 71.42.119.84:63190]     from app.app import app as application
[Thu Nov 03 03:44:04.106259 2016] [wsgi:error] [pid 5953:tid 140141997831936] [client 71.42.119.84:63190]   File "/var/www/cs373f-idb/app/app.py", line 9, in <module>
[Thu Nov 03 03:44:04.106267 2016] [wsgi:error] [pid 5953:tid 140141997831936] [client 71.42.119.84:63190]     import models
[Thu Nov 03 03:44:04.106312 2016] [wsgi:error] [pid 5953:tid 140141997831936] [client 71.42.119.84:63190] ImportError: No module named 'models'
[Thu Nov 03 03:44:06.195252 2016] [wsgi:error] [pid 5953:tid 140141981046528] [client 71.42.119.84:63264] mod_wsgi (pid=5953): Target WSGI script '/var/www/cs373f-idb/app.wsgi' cannot be loaded as Python module.
[Thu Nov 03 03:44:06.195374 2016] [wsgi:error] [pid 5953:tid 140141981046528] [client 71.42.119.84:63264] mod_wsgi (pid=5953): Exception occurred processing WSGI script '/var/www/cs373f-idb/app.wsgi'.
[Thu Nov 03 03:44:06.195557 2016] [wsgi:error] [pid 5953:tid 140141981046528] [client 71.42.119.84:63264] Traceback (most recent call last):
[Thu Nov 03 03:44:06.195650 2016] [wsgi:error] [pid 5953:tid 140141981046528] [client 71.42.119.84:63264]   File "/var/www/cs373f-idb/app.wsgi", line 7, in <module>
[Thu Nov 03 03:44:06.195663 2016] [wsgi:error] [pid 5953:tid 140141981046528] [client 71.42.119.84:63264]     from app.app import app as application
[Thu Nov 03 03:44:06.195679 2016] [wsgi:error] [pid 5953:tid 140141981046528] [client 71.42.119.84:63264]   File "/var/www/cs373f-idb/app/app.py", line 9, in <module>
[Thu Nov 03 03:44:06.195686 2016] [wsgi:error] [pid 5953:tid 140141981046528] [client 71.42.119.84:63264]     import models
[Thu Nov 03 03:44:06.195718 2016] [wsgi:error] [pid 5953:tid 140141981046528] [client 71.42.119.84:63264] ImportError: No module named 'models'
[Thu Nov 03 03:45:19.079534 2016] [wsgi:error] [pid 5953:tid 140141947475712] [client 71.42.119.84:63566] mod_wsgi (pid=5953): Target WSGI script '/var/www/cs373f-idb/app.wsgi' cannot be loaded as Python module.
[Thu Nov 03 03:45:19.079687 2016] [wsgi:error] [pid 5953:tid 140141947475712] [client 71.42.119.84:63566] mod_wsgi (pid=5953): Exception occurred processing WSGI script '/var/www/cs373f-idb/app.wsgi'.
[Thu Nov 03 03:45:19.079886 2016] [wsgi:error] [pid 5953:tid 140141947475712] [client 71.42.119.84:63566] Traceback (most recent call last):
[Thu Nov 03 03:45:19.080005 2016] [wsgi:error] [pid 5953:tid 140141947475712] [client 71.42.119.84:63566]   File "/var/www/cs373f-idb/app.wsgi", line 7, in <module>
[Thu Nov 03 03:45:19.080017 2016] [wsgi:error] [pid 5953:tid 140141947475712] [client 71.42.119.84:63566]     from app.app import app as application
[Thu Nov 03 03:45:19.080032 2016] [wsgi:error] [pid 5953:tid 140141947475712] [client 71.42.119.84:63566]   File "/var/www/cs373f-idb/app/app.py", line 9, in <module>
[Thu Nov 03 03:45:19.080040 2016] [wsgi:error] [pid 5953:tid 140141947475712] [client 71.42.119.84:63566]     import models
[Thu Nov 03 03:45:19.080122 2016] [wsgi:error] [pid 5953:tid 140141947475712] [client 71.42.119.84:63566] ImportError: No module named 'models'
[Thu Nov 03 03:45:31.613023 2016] [wsgi:error] [pid 5953:tid 140141972653824] [client 71.42.119.84:64002] mod_wsgi (pid=5953): Target WSGI script '/var/www/cs373f-idb/app.wsgi' cannot be loaded as Python module.
[Thu Nov 03 03:45:31.613224 2016] [wsgi:error] [pid 5953:tid 140141972653824] [client 71.42.119.84:64002] mod_wsgi (pid=5953): Exception occurred processing WSGI script '/var/www/cs373f-idb/app.wsgi'.
[Thu Nov 03 03:45:31.613522 2016] [wsgi:error] [pid 5953:tid 140141972653824] [client 71.42.119.84:64002] Traceback (most recent call last):
[Thu Nov 03 03:45:31.613611 2016] [wsgi:error] [pid 5953:tid 140141972653824] [client 71.42.119.84:64002]   File "/var/www/cs373f-idb/app.wsgi", line 7, in <module>
[Thu Nov 03 03:45:31.613634 2016] [wsgi:error] [pid 5953:tid 140141972653824] [client 71.42.119.84:64002]     from app.app import app as application
[Thu Nov 03 03:45:31.613673 2016] [wsgi:error] [pid 5953:tid 140141972653824] [client 71.42.119.84:64002]   File "/var/www/cs373f-idb/app/app.py", line 9, in <module>
[Thu Nov 03 03:45:31.613691 2016] [wsgi:error] [pid 5953:tid 140141972653824] [client 71.42.119.84:64002]     import models
[Thu Nov 03 03:45:31.613759 2016] [wsgi:error] [pid 5953:tid 140141972653824] [client 71.42.119.84:64002] ImportError: No module named 'models'
[Thu Nov 03 03:45:38.679580 2016] [wsgi:error] [pid 5953:tid 140142129039104] [client 71.42.119.84:64001] mod_wsgi (pid=5953): Target WSGI script '/var/www/cs373f-idb/app.wsgi' cannot be loaded as Python module.
[Thu Nov 03 03:45:38.679798 2016] [wsgi:error] [pid 5953:tid 140142129039104] [client 71.42.119.84:64001] mod_wsgi (pid=5953): Exception occurred processing WSGI script '/var/www/cs373f-idb/app.wsgi'.
[Thu Nov 03 03:45:38.680007 2016] [wsgi:error] [pid 5953:tid 140142129039104] [client 71.42.119.84:64001] Traceback (most recent call last):
[Thu Nov 03 03:45:38.680080 2016] [wsgi:error] [pid 5953:tid 140142129039104] [client 71.42.119.84:64001]   File "/var/www/cs373f-idb/app.wsgi", line 7, in <module>
[Thu Nov 03 03:45:38.680092 2016] [wsgi:error] [pid 5953:tid 140142129039104] [client 71.42.119.84:64001]     from app.app import app as application
[Thu Nov 03 03:45:38.680107 2016] [wsgi:error] [pid 5953:tid 140142129039104] [client 71.42.119.84:64001]   File "/var/www/cs373f-idb/app/app.py", line 9, in <module>
[Thu Nov 03 03:45:38.680115 2016] [wsgi:error] [pid 5953:tid 140142129039104] [client 71.42.119.84:64001]     import models
[Thu Nov 03 03:45:38.680146 2016] [wsgi:error] [pid 5953:tid 140142129039104] [client 71.42.119.84:64001] ImportError: No module named 'models'
[Thu Nov 03 03:46:21.296566 2016] [wsgi:error] [pid 5953:tid 140142120646400] [client 71.42.119.84:63625] mod_wsgi (pid=5953): Target WSGI script '/var/www/cs373f-idb/app.wsgi' cannot be loaded as Python module.
[Thu Nov 03 03:46:21.296676 2016] [wsgi:error] [pid 5953:tid 140142120646400] [client 71.42.119.84:63625] mod_wsgi (pid=5953): Exception occurred processing WSGI script '/var/www/cs373f-idb/app.wsgi'.
[Thu Nov 03 03:46:21.296841 2016] [wsgi:error] [pid 5953:tid 140142120646400] [client 71.42.119.84:63625] Traceback (most recent call last):
[Thu Nov 03 03:46:21.296889 2016] [wsgi:error] [pid 5953:tid 140142120646400] [client 71.42.119.84:63625]   File "/var/www/cs373f-idb/app.wsgi", line 7, in <module>
[Thu Nov 03 03:46:21.296901 2016] [wsgi:error] [pid 5953:tid 140142120646400] [client 71.42.119.84:63625]     from app.app import app as application
[Thu Nov 03 03:46:21.296916 2016] [wsgi:error] [pid 5953:tid 140142120646400] [client 71.42.119.84:63625]   File "/var/www/cs373f-idb/app/app.py", line 9, in <module>
[Thu Nov 03 03:46:21.296924 2016] [wsgi:error] [pid 5953:tid 140142120646400] [client 71.42.119.84:63625]     import models
[Thu Nov 03 03:46:21.296956 2016] [wsgi:error] [pid 5953:tid 140142120646400] [client 71.42.119.84:63625] ImportError: No module named 'models'
[Thu Nov 03 03:46:24.640216 2016] [wsgi:error] [pid 5953:tid 140142112253696] [client 71.42.119.84:63628] mod_wsgi (pid=5953): Target WSGI script '/var/www/cs373f-idb/app.wsgi' cannot be loaded as Python module.
[Thu Nov 03 03:46:24.640328 2016] [wsgi:error] [pid 5953:tid 140142112253696] [client 71.42.119.84:63628] mod_wsgi (pid=5953): Exception occurred processing WSGI script '/var/www/cs373f-idb/app.wsgi'.
[Thu Nov 03 03:46:24.640496 2016] [wsgi:error] [pid 5953:tid 140142112253696] [client 71.42.119.84:63628] Traceback (most recent call last):
[Thu Nov 03 03:46:24.640542 2016] [wsgi:error] [pid 5953:tid 140142112253696] [client 71.42.119.84:63628]   File "/var/www/cs373f-idb/app.wsgi", line 7, in <module>
[Thu Nov 03 03:46:24.640553 2016] [wsgi:error] [pid 5953:tid 140142112253696] [client 71.42.119.84:63628]     from app.app import app as application
[Thu Nov 03 03:46:24.640568 2016] [wsgi:error] [pid 5953:tid 140142112253696] [client 71.42.119.84:63628]   File "/var/www/cs373f-idb/app/app.py", line 9, in <module>
[Thu Nov 03 03:46:24.640576 2016] [wsgi:error] [pid 5953:tid 140142112253696] [client 71.42.119.84:63628]     import models
[Thu Nov 03 03:46:24.640607 2016] [wsgi:error] [pid 5953:tid 140142112253696] [client 71.42.119.84:63628] ImportError: No module named 'models'
[Thu Nov 03 03:46:34.661948 2016] [wsgi:error] [pid 5953:tid 140141955868416] [client 71.42.119.84:63826] mod_wsgi (pid=5953): Target WSGI script '/var/www/cs373f-idb/app.wsgi' cannot be loaded as Python module.
[Thu Nov 03 03:46:34.662115 2016] [wsgi:error] [pid 5953:tid 140141955868416] [client 71.42.119.84:63826] mod_wsgi (pid=5953): Exception occurred processing WSGI script '/var/www/cs373f-idb/app.wsgi'.
[Thu Nov 03 03:46:34.662356 2016] [wsgi:error] [pid 5953:tid 140141955868416] [client 71.42.119.84:63826] Traceback (most recent call last):
[Thu Nov 03 03:46:34.662430 2016] [wsgi:error] [pid 5953:tid 140141955868416] [client 71.42.119.84:63826]   File "/var/www/cs373f-idb/app.wsgi", line 7, in <module>
[Thu Nov 03 03:46:34.662448 2016] [wsgi:error] [pid 5953:tid 140141955868416] [client 71.42.119.84:63826]     from app.app import app as application
[Thu Nov 03 03:46:34.662538 2016] [wsgi:error] [pid 5953:tid 140141955868416] [client 71.42.119.84:63826]   File "/var/www/cs373f-idb/app/app.py", line 9, in <module>
[Thu Nov 03 03:46:34.662556 2016] [wsgi:error] [pid 5953:tid 140141955868416] [client 71.42.119.84:63826]     import models
[Thu Nov 03 03:46:34.662606 2016] [wsgi:error] [pid 5953:tid 140141955868416] [client 71.42.119.84:63826] ImportError: No module named 'models'
[Thu Nov 03 03:47:22.238849 2016] [wsgi:error] [pid 5953:tid 140141871941376] [client 71.42.119.84:63996] mod_wsgi (pid=5953): Target WSGI script '/var/www/cs373f-idb/app.wsgi' cannot be loaded as Python module.
[Thu Nov 03 03:47:22.238964 2016] [wsgi:error] [pid 5953:tid 140141871941376] [client 71.42.119.84:63996] mod_wsgi (pid=5953): Exception occurred processing WSGI script '/var/www/cs373f-idb/app.wsgi'.
[Thu Nov 03 03:47:22.239126 2016] [wsgi:error] [pid 5953:tid 140141871941376] [client 71.42.119.84:63996] Traceback (most recent call last):
[Thu Nov 03 03:47:22.239173 2016] [wsgi:error] [pid 5953:tid 140141871941376] [client 71.42.119.84:63996]   File "/var/www/cs373f-idb/app.wsgi", line 7, in <module>
[Thu Nov 03 03:47:22.239184 2016] [wsgi:error] [pid 5953:tid 140141871941376] [client 71.42.119.84:63996]     from app.app import app as application
[Thu Nov 03 03:47:22.239199 2016] [wsgi:error] [pid 5953:tid 140141871941376] [client 71.42.119.84:63996]   File "/var/www/cs373f-idb/app/app.py", line 9, in <module>
[Thu Nov 03 03:47:22.239207 2016] [wsgi:error] [pid 5953:tid 140141871941376] [client 71.42.119.84:63996]     import models
[Thu Nov 03 03:47:22.239239 2016] [wsgi:error] [pid 5953:tid 140141871941376] [client 71.42.119.84:63996] ImportError: No module named 'models'
[Thu Nov 03 03:47:24.567126 2016] [wsgi:error] [pid 5953:tid 140141863548672] [client 71.42.119.84:63995] mod_wsgi (pid=5953): Target WSGI script '/var/www/cs373f-idb/app.wsgi' cannot be loaded as Python module.
[Thu Nov 03 03:47:24.567281 2016] [wsgi:error] [pid 5953:tid 140141863548672] [client 71.42.119.84:63995] mod_wsgi (pid=5953): Exception occurred processing WSGI script '/var/www/cs373f-idb/app.wsgi'.
[Thu Nov 03 03:47:24.567525 2016] [wsgi:error] [pid 5953:tid 140141863548672] [client 71.42.119.84:63995] Traceback (most recent call last):
[Thu Nov 03 03:47:24.567599 2016] [wsgi:error] [pid 5953:tid 140141863548672] [client 71.42.119.84:63995]   File "/var/www/cs373f-idb/app.wsgi", line 7, in <module>
[Thu Nov 03 03:47:24.567617 2016] [wsgi:error] [pid 5953:tid 140141863548672] [client 71.42.119.84:63995]     from app.app import app as application
[Thu Nov 03 03:47:24.567715 2016] [wsgi:error] [pid 5953:tid 140141863548672] [client 71.42.119.84:63995]   File "/var/www/cs373f-idb/app/app.py", line 9, in <module>
[Thu Nov 03 03:47:24.567728 2016] [wsgi:error] [pid 5953:tid 140141863548672] [client 71.42.119.84:63995]     import models
[Thu Nov 03 03:47:24.567762 2016] [wsgi:error] [pid 5953:tid 140141863548672] [client 71.42.119.84:63995] ImportError: No module named 'models'
[Thu Nov 03 06:27:38.026325 2016] [wsgi:error] [pid 9128:tid 139679145510656] [client 71.42.119.84:63412] mod_wsgi (pid=9128): Target WSGI script '/var/www/cs373f-idb/app.wsgi' cannot be loaded as Python module., referer: http://vgidb.me/
[Thu Nov 03 06:27:38.026481 2016] [wsgi:error] [pid 9128:tid 139679145510656] [client 71.42.119.84:63412] mod_wsgi (pid=9128): Exception occurred processing WSGI script '/var/www/cs373f-idb/app.wsgi'., referer: http://vgidb.me/
[Thu Nov 03 06:27:38.027379 2016] [wsgi:error] [pid 9128:tid 139679145510656] [client 71.42.119.84:63412] Traceback (most recent call last):, referer: http://vgidb.me/
[Thu Nov 03 06:27:38.027449 2016] [wsgi:error] [pid 9128:tid 139679145510656] [client 71.42.119.84:63412]   File "/var/www/cs373f-idb/app.wsgi", line 7, in <module>, referer: http://vgidb.me/
[Thu Nov 03 06:27:38.027465 2016] [wsgi:error] [pid 9128:tid 139679145510656] [client 71.42.119.84:63412]     from app.app import app as application, referer: http://vgidb.me/
[Thu Nov 03 06:27:38.027498 2016] [wsgi:error] [pid 9128:tid 139679145510656] [client 71.42.119.84:63412]   File "/var/www/cs373f-idb/app/app.py", line 8, in <module>, referer: http://vgidb.me/
[Thu Nov 03 06:27:38.027507 2016] [wsgi:error] [pid 9128:tid 139679145510656] [client 71.42.119.84:63412]     from tests import runTestsOut, referer: http://vgidb.me/
[Thu Nov 03 06:27:38.027557 2016] [wsgi:error] [pid 9128:tid 139679145510656] [client 71.42.119.84:63412] ImportError: No module named 'tests', referer: http://vgidb.me/
[Thu Nov 03 06:27:38.684589 2016] [wsgi:error] [pid 9129:tid 139679162296064] [client 71.42.119.84:63421] mod_wsgi (pid=9129): Target WSGI script '/var/www/cs373f-idb/app.wsgi' cannot be loaded as Python module., referer: http://vgidb.me/
[Thu Nov 03 06:27:38.684736 2016] [wsgi:error] [pid 9129:tid 139679162296064] [client 71.42.119.84:63421] mod_wsgi (pid=9129): Exception occurred processing WSGI script '/var/www/cs373f-idb/app.wsgi'., referer: http://vgidb.me/
[Thu Nov 03 06:27:38.685619 2016] [wsgi:error] [pid 9129:tid 139679162296064] [client 71.42.119.84:63421] Traceback (most recent call last):, referer: http://vgidb.me/
[Thu Nov 03 06:27:38.685676 2016] [wsgi:error] [pid 9129:tid 139679162296064] [client 71.42.119.84:63421]   File "/var/www/cs373f-idb/app.wsgi", line 7, in <module>, referer: http://vgidb.me/
[Thu Nov 03 06:27:38.685688 2016] [wsgi:error] [pid 9129:tid 139679162296064] [client 71.42.119.84:63421]     from app.app import app as application, referer: http://vgidb.me/
[Thu Nov 03 06:27:38.685704 2016] [wsgi:error] [pid 9129:tid 139679162296064] [client 71.42.119.84:63421]   File "/var/www/cs373f-idb/app/app.py", line 8, in <module>, referer: http://vgidb.me/
[Thu Nov 03 06:27:38.685713 2016] [wsgi:error] [pid 9129:tid 139679162296064] [client 71.42.119.84:63421]     from tests import runTestsOut, referer: http://vgidb.me/
[Thu Nov 03 06:27:38.685753 2016] [wsgi:error] [pid 9129:tid 139679162296064] [client 71.42.119.84:63421] ImportError: No module named 'tests', referer: http://vgidb.me/
[Thu Nov 03 06:27:47.648806 2016] [wsgi:error] [pid 9129:tid 139679137109760] [client 71.42.119.84:63704] mod_wsgi (pid=9129): Target WSGI script '/var/www/cs373f-idb/app.wsgi' cannot be loaded as Python module.
[Thu Nov 03 06:27:47.648983 2016] [wsgi:error] [pid 9129:tid 139679137109760] [client 71.42.119.84:63704] mod_wsgi (pid=9129): Exception occurred processing WSGI script '/var/www/cs373f-idb/app.wsgi'.
[Thu Nov 03 06:27:47.649247 2016] [wsgi:error] [pid 9129:tid 139679137109760] [client 71.42.119.84:63704] Traceback (most recent call last):
[Thu Nov 03 06:27:47.649326 2016] [wsgi:error] [pid 9129:tid 139679137109760] [client 71.42.119.84:63704]   File "/var/www/cs373f-idb/app.wsgi", line 7, in <module>
[Thu Nov 03 06:27:47.649344 2016] [wsgi:error] [pid 9129:tid 139679137109760] [client 71.42.119.84:63704]     from app.app import app as application
[Thu Nov 03 06:27:47.649368 2016] [wsgi:error] [pid 9129:tid 139679137109760] [client 71.42.119.84:63704]   File "/var/www/cs373f-idb/app/app.py", line 8, in <module>
[Thu Nov 03 06:27:47.649381 2016] [wsgi:error] [pid 9129:tid 139679137109760] [client 71.42.119.84:63704]     from tests import runTestsOut
[Thu Nov 03 06:27:47.649432 2016] [wsgi:error] [pid 9129:tid 139679137109760] [client 71.42.119.84:63704] ImportError: No module named 'tests'
[Thu Nov 03 06:29:48.844312 2016] [wsgi:error] [pid 9261:tid 139800774371072] [client 71.42.119.84:62767] mod_wsgi (pid=9261): Target WSGI script '/var/www/cs373f-idb/app.wsgi' cannot be loaded as Python module.
[Thu Nov 03 06:29:48.844477 2016] [wsgi:error] [pid 9261:tid 139800774371072] [client 71.42.119.84:62767] mod_wsgi (pid=9261): Exception occurred processing WSGI script '/var/www/cs373f-idb/app.wsgi'.
[Thu Nov 03 06:29:48.845165 2016] [wsgi:error] [pid 9261:tid 139800774371072] [client 71.42.119.84:62767] Traceback (most recent call last):
[Thu Nov 03 06:29:48.845218 2016] [wsgi:error] [pid 9261:tid 139800774371072] [client 71.42.119.84:62767]   File "/var/www/cs373f-idb/app.wsgi", line 7, in <module>
[Thu Nov 03 06:29:48.845255 2016] [wsgi:error] [pid 9261:tid 139800774371072] [client 71.42.119.84:62767]     from app.app import app as application
[Thu Nov 03 06:29:48.845277 2016] [wsgi:error] [pid 9261:tid 139800774371072] [client 71.42.119.84:62767]   File "/var/www/cs373f-idb/app/app.py", line 8, in <module>
[Thu Nov 03 06:29:48.845286 2016] [wsgi:error] [pid 9261:tid 139800774371072] [client 71.42.119.84:62767]     from tests import runTestsOut
[Thu Nov 03 06:29:48.845324 2016] [wsgi:error] [pid 9261:tid 139800774371072] [client 71.42.119.84:62767] ImportError: No module named 'tests'
[Thu Nov 03 06:31:30.266961 2016] [wsgi:error] [pid 9383:tid 140013241100032] [client 71.42.119.84:63687] mod_wsgi (pid=9383): Target WSGI script '/var/www/cs373f-idb/app.wsgi' cannot be loaded as Python module.
[Thu Nov 03 06:31:30.267132 2016] [wsgi:error] [pid 9383:tid 140013241100032] [client 71.42.119.84:63687] mod_wsgi (pid=9383): Exception occurred processing WSGI script '/var/www/cs373f-idb/app.wsgi'.
[Thu Nov 03 06:31:30.268157 2016] [wsgi:error] [pid 9383:tid 140013241100032] [client 71.42.119.84:63687] Traceback (most recent call last):
[Thu Nov 03 06:31:30.268222 2016] [wsgi:error] [pid 9383:tid 140013241100032] [client 71.42.119.84:63687]   File "/var/www/cs373f-idb/app.wsgi", line 7, in <module>
[Thu Nov 03 06:31:30.268235 2016] [wsgi:error] [pid 9383:tid 140013241100032] [client 71.42.119.84:63687]     from app.app import app as application
[Thu Nov 03 06:31:30.268250 2016] [wsgi:error] [pid 9383:tid 140013241100032] [client 71.42.119.84:63687]   File "/var/www/cs373f-idb/app/app.py", line 8, in <module>
[Thu Nov 03 06:31:30.268258 2016] [wsgi:error] [pid 9383:tid 140013241100032] [client 71.42.119.84:63687]     from app.tests import runTestsOut
[Thu Nov 03 06:31:30.268272 2016] [wsgi:error] [pid 9383:tid 140013241100032] [client 71.42.119.84:63687]   File "/var/www/cs373f-idb/app/tests.py", line 4, in <module>
[Thu Nov 03 06:31:30.268279 2016] [wsgi:error] [pid 9383:tid 140013241100032] [client 71.42.119.84:63687]     from models \t\timport *
[Thu Nov 03 06:31:30.268314 2016] [wsgi:error] [pid 9383:tid 140013241100032] [client 71.42.119.84:63687] ImportError: No module named 'models'
[Thu Nov 03 06:31:40.148701 2016] [wsgi:error] [pid 9384:tid 140013173958400] [client 71.42.119.84:64008] mod_wsgi (pid=9384): Target WSGI script '/var/www/cs373f-idb/app.wsgi' cannot be loaded as Python module.
[Thu Nov 03 06:31:40.148923 2016] [wsgi:error] [pid 9384:tid 140013173958400] [client 71.42.119.84:64008] mod_wsgi (pid=9384): Exception occurred processing WSGI script '/var/www/cs373f-idb/app.wsgi'.
[Thu Nov 03 06:31:40.149949 2016] [wsgi:error] [pid 9384:tid 140013173958400] [client 71.42.119.84:64008] Traceback (most recent call last):
[Thu Nov 03 06:31:40.150046 2016] [wsgi:error] [pid 9384:tid 140013173958400] [client 71.42.119.84:64008]   File "/var/www/cs373f-idb/app.wsgi", line 7, in <module>
[Thu Nov 03 06:31:40.150069 2016] [wsgi:error] [pid 9384:tid 140013173958400] [client 71.42.119.84:64008]     from app.app import app as application
[Thu Nov 03 06:31:40.150103 2016] [wsgi:error] [pid 9384:tid 140013173958400] [client 71.42.119.84:64008]   File "/var/www/cs373f-idb/app/app.py", line 8, in <module>
[Thu Nov 03 06:31:40.150115 2016] [wsgi:error] [pid 9384:tid 140013173958400] [client 71.42.119.84:64008]     from app.tests import runTestsOut
[Thu Nov 03 06:31:40.150130 2016] [wsgi:error] [pid 9384:tid 140013173958400] [client 71.42.119.84:64008]   File "/var/www/cs373f-idb/app/tests.py", line 4, in <module>
[Thu Nov 03 06:31:40.150138 2016] [wsgi:error] [pid 9384:tid 140013173958400] [client 71.42.119.84:64008]     from models \t\timport *
[Thu Nov 03 06:31:40.150178 2016] [wsgi:error] [pid 9384:tid 140013173958400] [client 71.42.119.84:64008] ImportError: No module named 'models'
